### PR TITLE
using Appveyor for continuous build

### PR DESCRIPTION
**Pull request by bennage**
details about the service are here http://www.appveyor.com/
@lbrader you might be interested in this.
@mj1856 can you give this a quick look over?

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bennage__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (christb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bennage** [comment]
Notice that the build status of this pull request is included. :smiley:

**Comment by mj1856** [comment]
Hmmm..  I see in the build output none of the tests are running.

```
Skipping assembly (no tests match the specified filter).
```

I also see `/trait "category=Unit"`, while in our code we have `[Trait("Category", "Unit")]`.   Is it case-sensitive perhaps?

**Comment by bennage** [comment]
Blerg. The integration tests were failing before. When this passed, I assumed the tests were running.

**Comment by bennage** [comment]
It's not the case that causing the problem. I'm upgrading to xunit 2 to see if that changes anything.

**Comment by bennage** [comment]
Okay, I'm seeing passed tests now. I think that xunit 1.9.x was _part_ of the problem.
The traits are not consistently applied across the tests though (and there are a few odd tests).
I'd like to work that out in a future pr. Do you see any other problems?

**Comment by mj1856** [comment]
LGTM

**Pull request merged**
