### PR TITLE
adding standard file headers

### PR DESCRIPTION
**Pull request by bennage**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bennage__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (christb). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bennage** [comment]
I completely redid the file headers using R#.

**Comment by francischeung** [comment]
Looks pretty good. You might want to consider putting one line of white space between the license header and the code. Otherwise it is ready to merge. If you wish to go with code as-is, let me know and I'll merge.

**Comment by bennage** [comment]
Yeah, I like the extra line but (using R#) I had to apply a code reformat to get the extra line and that ended up changing more than I wanted. I'm okay merging this as-is.

**Pull request merged**
